### ISSUE TITLE
Does not compile full file if injecting imports via stream

### ISSUE THREAD

**Issue by dinglidingli** [skyrpex/gulp-less-watcher#2] opened 2015-09-08 00:02 UTC
I'm using the plugin gulp-insert (https://github.com/rschmukler/gulp-insert) to modify the stream contents and insert imports into my build file dynamically.

It seems like gulp-less-watcher is only watching the original LESS build file and not the one being passed through the stream. 

I'm calling it in a similar way to the code below:

```
return gulp.src(glob)
    .pipe(insert.prepend(importString))
    .pipe(watchLess())
    .pipe(less())
    .pipe(gulp.dest(targetDir));
```

This is particularly noticeable if the dynamically inserted imports create variables or mixins which are used by later files.

**Comment by skyrpex** [comment] 2015-09-09 13:28
Hi @chrisdingli,

have you tried inserting after watchLess?

``` js
return gulp.src(glob)
    .pipe(watchLess())
    .pipe(insert.prepend(importString))
    .pipe(less())
    .pipe(gulp.dest(targetDir));
```

**Comment by dinglidingli** [comment] 2015-09-25 05:48
@skyrpex Sorry for the late reply. It complains about missing mixins that are included dynamically:
[15:47:04] gulp-notify: [Error running Gulp] Error: .slide-feature-hidden is undefined in file C:\Dev\git\web\src\main\webapp\bundles\car\less\navbarButtonsVisibility.less line no. 11

**Comment by skyrpex** [comment] 2015-09-28 06:02
Hmm, I see... the problem is that you must insert that importString before the file arrives to watchLess(). Actually, the current approach won't work in your case.

You need a third step...

``` js
return gulp.src(glob)
    // Use gulp-watch to watch the original source
    .pipe(watch(src))
    // Insert content dynamically
    .pipe(insert.prepend(importString))
    // Use a modified version of gulp-watch-less that just watchs imports and not the original file
    .pipe(watchLess())
    .pipe(less())
    .pipe(gulp.dest(targetDir));
```

**Comment by skyrpex** [comment] 2015-10-06 13:26
I'm closing this since this isn't directly supported by this plugin.

**Closed as completed by skyrpex** 2015-10-06 13:26 UTC
